name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.TARGET.OS }}
    defaults:
      run:
        shell: bash
        working-directory: 2.7.2-970404
    strategy:
      fail-fast: false
      matrix:
        TARGET:
          - {
              OS: 'ubuntu-latest',
              CFLAGS: '-static -std=gnu89 -O2 -DHAVE_VPRINTF',
              HOST: 'i386-pc-linux',
              ARCHIVE_NAME: 'SN64-gcc-2.7.2-970404-linux.tar.gz'
            }
          - {
              OS: 'macos-latest',
              CFLAGS: '-DDARWIN -std=gnu89 -O2 -DHAVE_VPRINTF -Wno-return-type -Wno-error -Wno-implicit-function-declaration',
              HOST: 'i386-apple-darwin',
              ARCHIVE_NAME: 'SN64-gcc-2.7.2-970404-mac.tar.gz'
            }

    name: Building SN64 gcc 2.7.2-970404 for ${{ matrix.TARGET.OS }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies (Ubuntu)
        if: matrix.TARGET.OS == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bison file gperf gcc gcc-multilib
      - name: Make
        run: |
          make cpp cc1 xgcc cc1plus g++ CFLAGS="${{ matrix.TARGET.CFLAGS }}"
      - name: Test for cc1
        run: |
          test -f cc1
          file cc1
      - name: Create release archive
        run: |
          cp xgcc gcc
          tar -czf ../${{ matrix.TARGET.ARCHIVE_NAME }} cpp cc1 gcc cc1plus g++
      - name: Upload archive
        uses: actions/upload-artifact@v2
        with:
          name: SN64-gcc-2.7.2-970404-${{ matrix.TARGET.OS }}
          path: |
            ${{ matrix.TARGET.ARCHIVE_NAME }}
      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ matrix.TARGET.ARCHIVE_NAME }}
